### ISSUE TITLE
Advanced example

### ISSUE THREAD

**Issue by richp10** [jeromer/sqrible#1]
The example template in the advanced folder seems to be the same as the simple one.. I wonder if you could provide more examples of how the utility can be used... such as the template to produce the 'generated.go' shown in the video. 

Your version seems to be much better than pgxdata at assigning the correct data types.. so I hope I can figure out more comprehensive templates!

**Comment by jeromer** [comment]
Hi @richp10 

First of all I am sorry for replying so late I got no email notifications about this issue.

I provided a full fledged advanced example so you can have a look at it.

Any feedback welcome.

:)
